// Generated by gencpp from file rosserial_tivac_tutorials/ColorRGBAResponse.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_TIVAC_TUTORIALS_MESSAGE_COLORRGBARESPONSE_H
#define ROSSERIAL_TIVAC_TUTORIALS_MESSAGE_COLORRGBARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosserial_tivac_tutorials
{
template <class ContainerAllocator>
struct ColorRGBAResponse_
{
  typedef ColorRGBAResponse_<ContainerAllocator> Type;

  ColorRGBAResponse_()
    : result(false)  {
    }
  ColorRGBAResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ColorRGBAResponse_

typedef ::rosserial_tivac_tutorials::ColorRGBAResponse_<std::allocator<void> > ColorRGBAResponse;

typedef boost::shared_ptr< ::rosserial_tivac_tutorials::ColorRGBAResponse > ColorRGBAResponsePtr;
typedef boost::shared_ptr< ::rosserial_tivac_tutorials::ColorRGBAResponse const> ColorRGBAResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosserial_tivac_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosserial_tivac_tutorials': ['/home/wesley/Sources/TUhandControl/TivaC/catkin_rosserial_tut/src/rosserial_tivac_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosserial_tivac_tutorials/ColorRGBAResponse";
  }

  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorRGBAResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosserial_tivac_tutorials::ColorRGBAResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSERIAL_TIVAC_TUTORIALS_MESSAGE_COLORRGBARESPONSE_H
