// Generated by gencpp from file rosserial_tivac_tutorials/ColorRGBARequest.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_TIVAC_TUTORIALS_MESSAGE_COLORRGBAREQUEST_H
#define ROSSERIAL_TIVAC_TUTORIALS_MESSAGE_COLORRGBAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>

namespace rosserial_tivac_tutorials
{
template <class ContainerAllocator>
struct ColorRGBARequest_
{
  typedef ColorRGBARequest_<ContainerAllocator> Type;

  ColorRGBARequest_()
    : color()  {
    }
  ColorRGBARequest_(const ContainerAllocator& _alloc)
    : color(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _color_type;
  _color_type color;




  typedef boost::shared_ptr< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> const> ConstPtr;

}; // struct ColorRGBARequest_

typedef ::rosserial_tivac_tutorials::ColorRGBARequest_<std::allocator<void> > ColorRGBARequest;

typedef boost::shared_ptr< ::rosserial_tivac_tutorials::ColorRGBARequest > ColorRGBARequestPtr;
typedef boost::shared_ptr< ::rosserial_tivac_tutorials::ColorRGBARequest const> ColorRGBARequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosserial_tivac_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosserial_tivac_tutorials': ['/home/wesley/Sources/TUhandControl/TivaC/catkin_rosserial_tut/src/rosserial_tivac_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e04b62b1b39cd97e873789f0bb130e7";
  }

  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e04b62b1b39cd97ULL;
  static const uint64_t static_value2 = 0xe873789f0bb130e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosserial_tivac_tutorials/ColorRGBARequest";
  }

  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/ColorRGBA color\n\
\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
";
  }

  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorRGBARequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosserial_tivac_tutorials::ColorRGBARequest_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSERIAL_TIVAC_TUTORIALS_MESSAGE_COLORRGBAREQUEST_H
