// Generated by gencpp from file rosserial_tivac_tutorials/ColorRGBA.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_TIVAC_TUTORIALS_MESSAGE_COLORRGBA_H
#define ROSSERIAL_TIVAC_TUTORIALS_MESSAGE_COLORRGBA_H

#include <ros/service_traits.h>


#include <rosserial_tivac_tutorials/ColorRGBARequest.h>
#include <rosserial_tivac_tutorials/ColorRGBAResponse.h>


namespace rosserial_tivac_tutorials
{

struct ColorRGBA
{

typedef ColorRGBARequest Request;
typedef ColorRGBAResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ColorRGBA
} // namespace rosserial_tivac_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosserial_tivac_tutorials::ColorRGBA > {
  static const char* value()
  {
    return "f0106025071e27ff96990e664f228cc8";
  }

  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBA&) { return value(); }
};

template<>
struct DataType< ::rosserial_tivac_tutorials::ColorRGBA > {
  static const char* value()
  {
    return "rosserial_tivac_tutorials/ColorRGBA";
  }

  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBA&) { return value(); }
};


// service_traits::MD5Sum< ::rosserial_tivac_tutorials::ColorRGBARequest> should match 
// service_traits::MD5Sum< ::rosserial_tivac_tutorials::ColorRGBA > 
template<>
struct MD5Sum< ::rosserial_tivac_tutorials::ColorRGBARequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_tivac_tutorials::ColorRGBA >::value();
  }
  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBARequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_tivac_tutorials::ColorRGBARequest> should match 
// service_traits::DataType< ::rosserial_tivac_tutorials::ColorRGBA > 
template<>
struct DataType< ::rosserial_tivac_tutorials::ColorRGBARequest>
{
  static const char* value()
  {
    return DataType< ::rosserial_tivac_tutorials::ColorRGBA >::value();
  }
  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBARequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosserial_tivac_tutorials::ColorRGBAResponse> should match 
// service_traits::MD5Sum< ::rosserial_tivac_tutorials::ColorRGBA > 
template<>
struct MD5Sum< ::rosserial_tivac_tutorials::ColorRGBAResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_tivac_tutorials::ColorRGBA >::value();
  }
  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBAResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_tivac_tutorials::ColorRGBAResponse> should match 
// service_traits::DataType< ::rosserial_tivac_tutorials::ColorRGBA > 
template<>
struct DataType< ::rosserial_tivac_tutorials::ColorRGBAResponse>
{
  static const char* value()
  {
    return DataType< ::rosserial_tivac_tutorials::ColorRGBA >::value();
  }
  static const char* value(const ::rosserial_tivac_tutorials::ColorRGBAResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERIAL_TIVAC_TUTORIALS_MESSAGE_COLORRGBA_H
