# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rosserial_tivac_tutorials/Buttons.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Buttons(genpy.Message):
  _md5sum = "a78ccaade8fa723d1ebeb7b099042085"
  _type = "rosserial_tivac_tutorials/Buttons"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/Bool sw1
std_msgs/Bool sw2

================================================================================
MSG: std_msgs/Bool
bool data"""
  __slots__ = ['sw1','sw2']
  _slot_types = ['std_msgs/Bool','std_msgs/Bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sw1,sw2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Buttons, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sw1 is None:
        self.sw1 = std_msgs.msg.Bool()
      if self.sw2 is None:
        self.sw2 = std_msgs.msg.Bool()
    else:
      self.sw1 = std_msgs.msg.Bool()
      self.sw2 = std_msgs.msg.Bool()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.sw1.data, _x.sw2.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.sw1 is None:
        self.sw1 = std_msgs.msg.Bool()
      if self.sw2 is None:
        self.sw2 = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 2
      (_x.sw1.data, _x.sw2.data,) = _get_struct_2B().unpack(str[start:end])
      self.sw1.data = bool(self.sw1.data)
      self.sw2.data = bool(self.sw2.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.sw1.data, _x.sw2.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.sw1 is None:
        self.sw1 = std_msgs.msg.Bool()
      if self.sw2 is None:
        self.sw2 = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 2
      (_x.sw1.data, _x.sw2.data,) = _get_struct_2B().unpack(str[start:end])
      self.sw1.data = bool(self.sw1.data)
      self.sw2.data = bool(self.sw2.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
